
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart"
    firebase_app_distribution(
      app: "1:245672818453:android:31ee7ba3c09b42c3205b1c",
      testers: "fawziqeshta@gmail.com",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      apk_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      android_artifact_type: "APK",
      release_notes: "First Fastlane Firebase Distribution || CI/CD Integration"
    )
  end
end
